version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: olake-s3-test-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Optional: Create test bucket and upload sample files on startup
  minio-setup:
    image: minio/mc:latest
    container_name: olake-s3-test-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/olake-test-bucket --ignore-existing;
      echo 'MinIO setup complete! Bucket created: olake-test-bucket';
      echo 'Access MinIO Console at: http://localhost:9001';
      echo 'Username: minioadmin';
      echo 'Password: minioadmin';
      "

volumes:
  minio-data:
    driver: local
